import { Facility, FacilityAsset, FacilityCategory, FacilityInspectionSchedule } from './types';

export const FACILITY_CATEGORIES = ['강의실', '실습실', '행정사무실', '회의실', '도서관', '건물명'] as const;

export const normalizeFacilityCategory = (value: string): FacilityCategory => {
  if (value === '실험실') return '실습실';
  if (value === '체육시설' || value === '공용공간') return '건물명';
  if ((FACILITY_CATEGORIES as readonly string[]).includes(value)) return value as FacilityCategory;
  return '건물명';
};

export const FACILITY_STATUSES = ['운영중', '점검중', '예약중지'] as const;

export const DEFAULT_FACILITIES: Facility[] = [
  {
    id: 'facility_lecture_101',
    name: '본관 101 스마트 강의실',
    category: '강의실',
    capacity: 80,
    location: '본관 1층 101호',
    description: '전자칠판, 빔프로젝터, 무선마이크가 설치된 대형 강의실입니다.',
    status: '운영중',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'facility_meeting_3f',
    name: '본관 3층 대회의실',
    category: '회의실',
    capacity: 32,
    location: '본관 3층',
    description: '학과 회의와 외부 방문객 응대에 사용하는 회의실입니다.',
    status: '운영중',
    createdAt: '2026-05-02T09:00:00Z',
    updatedAt: '2026-05-02T09:00:00Z',
  },
  {
    id: 'facility_lab_safety',
    name: '공학관 공용 실습실',
    category: '실습실',
    capacity: 24,
    location: '공학관 4층',
    description: '연구실 안전 점검 대상 시설이며 시설관리팀 확인 후 주요 일정을 등록합니다.',
    status: '점검중',
    createdAt: '2026-05-03T09:00:00Z',
    updatedAt: '2026-05-03T09:00:00Z',
  },
  {
    id: 'facility_gym_main',
    name: '종합관 실내체육실',
    category: '건물명',
    capacity: 120,
    location: '종합관 B1',
    description: '체육 수업, 동아리 활동, 행사 준비 공간으로 사용하는 시설입니다.',
    status: '운영중',
    createdAt: '2026-05-04T09:00:00Z',
    updatedAt: '2026-05-04T09:00:00Z',
  },
];

export const DEFAULT_INSPECTION_SCHEDULES: FacilityInspectionSchedule[] = [
  {
    id: 'inspection_lab_safety_monthly',
    facilityId: 'facility_lab_safety',
    facilityName: '공학관 공용 실습실',
    title: '연구실 안전 정기점검',
    inspectionType: '연구실 안전',
    cycle: 'monthly',
    inspectorName: '김익현',
    dueDate: '2026-05-30',
    status: 'scheduled',
    notes: '화학물질 보관함, MSDS, 비상샤워기 상태를 함께 확인합니다.',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'inspection_electric_quarter',
    facilityId: 'facility_lecture_101',
    facilityName: '본관 101 스마트 강의실',
    title: '전기설비 분기 점검',
    inspectionType: '전기',
    cycle: 'quarterly',
    inspectorName: '이인혁',
    dueDate: '2026-06-07',
    status: 'scheduled',
    notes: '전자칠판 전원부, 콘센트 과열 흔적, 분전반 차단기 상태를 확인합니다.',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
  {
    id: 'inspection_gym_fire',
    facilityId: 'facility_gym_main',
    facilityName: '종합관 실내체육실',
    title: '소방 및 피난동선 점검',
    inspectionType: '소방',
    cycle: 'monthly',
    inspectorName: '오승훈',
    dueDate: '2026-05-24',
    status: 'scheduled',
    notes: '비상구 적치물, 유도등, 소화기 압력 상태를 확인합니다.',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
  },
];

export const DEFAULT_FACILITY_ASSETS: FacilityAsset[] = [
  {
    id: 'asset_lecture_projector',
    facilityId: 'facility_lecture_101',
    facilityName: '본관 101 스마트 강의실',
    name: '레이저 빔프로젝터',
    assetTag: 'FMS-LECTURE-PRJ-001',
    category: '영상장비',
    condition: 'good',
    status: 'active',
    managerName: '박성훈',
    purchasedAt: '2025-03-01',
    lastCheckedAt: '2026-05-10',
    value: 3200000,
    notes: '램프 수명과 HDMI 입력 상태 정상',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-10T09:00:00Z',
  },
  {
    id: 'asset_meeting_mic',
    facilityId: 'facility_meeting_3f',
    facilityName: '본관 3층 대회의실',
    name: '무선 회의 마이크 세트',
    assetTag: 'FMS-MEETING-MIC-003',
    category: '음향장비',
    condition: 'watch',
    status: 'active',
    managerName: '오승훈',
    purchasedAt: '2024-08-12',
    lastCheckedAt: '2026-05-18',
    value: 1450000,
    notes: '2번 마이크 배터리 접점 확인 필요',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-18T09:00:00Z',
  },
  {
    id: 'asset_lab_shower',
    facilityId: 'facility_lab_safety',
    facilityName: '공학관 공용 실습실',
    name: '비상샤워기 및 세안기',
    assetTag: 'FMS-LAB-SAFE-007',
    category: '안전설비',
    condition: 'repair',
    status: 'maintenance',
    managerName: '김익현',
    purchasedAt: '2023-02-15',
    lastCheckedAt: '2026-05-20',
    value: 980000,
    notes: '수압이 낮아 밸브와 배관 연결부 점검 중',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-20T09:00:00Z',
  },
  {
    id: 'asset_gym_air_fan',
    facilityId: 'facility_gym_main',
    facilityName: '종합관 실내체육실',
    name: '공조 순환팬',
    assetTag: 'FMS-GYM-HVAC-004',
    category: '기계설비',
    condition: 'good',
    status: 'active',
    managerName: '박희찬',
    purchasedAt: '2024-05-20',
    lastCheckedAt: '2026-05-22',
    value: 2100000,
    notes: '소음과 진동 모두 정상 범위',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-22T09:00:00Z',
  },
];
